-- =============================================================================
-- YouTube Mirror Bot — Comprehensive Supabase Schema
-- =============================================================================
-- Single source of truth for the 24/7 bot. Every table below is created if it
-- does not already exist; new columns are added when missing; indexes and the
-- helper views are created/replaced idempotently. Safe to run repeatedly.
--
-- RUN: open the Supabase Dashboard SQL Editor for this project and paste the
--      whole file, or run it through the `supabase` CLI / psql. The bot's
--      service key bypasses RLS; the permissive policies below additionally
--      allow the anon role to read state (used by status dashboards).
--
-- NOTE: this schema covers the MAIN supabase project
--       (https://zzxatvwjblfbaqzdxouw.supabase.co). The proxy database
--       (bytemjjijgwwcrxlgutf) is separate and unchanged.
-- =============================================================================

-- ─── Projects (one row per mirror bot deployment) ──────────────────────────
CREATE TABLE IF NOT EXISTS public.projects (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text NOT NULL,
    yt_client_id        text NOT NULL DEFAULT '',
    yt_client_secret    text NOT NULL DEFAULT '',
    yt_refresh_token    text NOT NULL DEFAULT '',
    github_token        text NOT NULL DEFAULT '',
    github_repo         text NOT NULL DEFAULT '',
    channels            text NOT NULL DEFAULT '',            -- CSV of @handles/IDs
    shortlink_provider  text NOT NULL DEFAULT 'vplink',
    shortlink_api_key   text NOT NULL DEFAULT '',
    warmup_days         integer NOT NULL DEFAULT 0,
    warmup_start        text NOT NULL DEFAULT '',
    comment_moderation  text NOT NULL DEFAULT 'heldForReview',
    mirror_title_prefix text NOT NULL DEFAULT '',
    deployed_at         text,
    uploads_per_day     integer NOT NULL DEFAULT 2,
    initial_backfill    integer NOT NULL DEFAULT 5,
    upload_schedule     text NOT NULL DEFAULT '',
    proxy_supabase_url  text NOT NULL DEFAULT '',
    proxy_supabase_key  text NOT NULL DEFAULT '',
    enabled             boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.projects
    ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true;

-- ─── Settings (generic key/value, JSON values — e.g. pending_hashes_N) ─────
CREATE TABLE IF NOT EXISTS public.settings (
    key         text PRIMARY KEY,
    value       jsonb NOT NULL DEFAULT 'null'::jsonb,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── Accounts (YouTube OAuth identities) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.accounts (
    name            text PRIMARY KEY,
    client_id       text NOT NULL DEFAULT '',
    client_secret   text NOT NULL DEFAULT '',
    refresh_token   text NOT NULL DEFAULT '',
    channel_id      text NOT NULL DEFAULT '',
    channel_name    text NOT NULL DEFAULT '',
    added_at        text,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Channels (source channels tracked) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.channels (
    id          text PRIMARY KEY,
    name        text NOT NULL DEFAULT '',
    url         text NOT NULL DEFAULT '',
    enabled     boolean NOT NULL DEFAULT true,
    added_at    text,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── Per-project upload state ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.upload_state (
    project_id          text PRIMARY KEY,
    account_created     text,
    warmup_start        text,
    warmup_complete     boolean NOT NULL DEFAULT false,
    first_upload_date   text,
    total_uploaded      bigint NOT NULL DEFAULT 0,
    last_upload_date    text,
    last_upload_hour    text,
    processed_hashes    jsonb NOT NULL DEFAULT '[]'::jsonb,  -- source video IDs mirrored
    filled_slots        jsonb NOT NULL DEFAULT '[]'::jsonb,
    filled_slots_date   text,
    yt_client_id        text NOT NULL DEFAULT '',
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ─── Upload log (audit trail of every uploaded mirror video) ───────────────
CREATE TABLE IF NOT EXISTS public.upload_logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      text NOT NULL DEFAULT '',
    upload_date     text NOT NULL DEFAULT '',                -- YYYY-MM-DD (UTC)
    upload_time     text NOT NULL DEFAULT '',                -- full ISO timestamp
    video_id        text NOT NULL DEFAULT '',                -- the MIRROR video id
    title           text NOT NULL DEFAULT '',
    short_url       text NOT NULL DEFAULT '',
    comment_id      text NOT NULL DEFAULT '',
    source_video_id text NOT NULL DEFAULT '',                -- the SOURCE video id
    source_channel  text NOT NULL DEFAULT '',                -- source channel @handle/id
    created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.upload_logs
    ADD COLUMN IF NOT EXISTS source_video_id text NOT NULL DEFAULT '';
ALTER TABLE public.upload_logs
    ADD COLUMN IF NOT EXISTS source_channel text NOT NULL DEFAULT '';

-- ─── Per-source-video mirror audit (one row per source→mirror mapping) ─────
CREATE TABLE IF NOT EXISTS public.mirror_state (
    project_id        text NOT NULL,
    source_channel    text NOT NULL DEFAULT '',
    source_video_id   text NOT NULL,
    mirrored_video_id text NOT NULL DEFAULT '',
    original_title    text NOT NULL DEFAULT '',
    mirrored_at       text,
    comment_id        text NOT NULL DEFAULT '',
    shortened_urls    jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (project_id, source_channel, source_video_id)
);

-- ─── Mirror stats ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mirror_stats (
    project_id      text PRIMARY KEY,
    total_mirrored  bigint NOT NULL DEFAULT 0,
    total_comments  bigint NOT NULL DEFAULT 0,
    total_shortened bigint NOT NULL DEFAULT 0,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Per-channel detection cursors (newest video seen) ─────────────────────
CREATE TABLE IF NOT EXISTS public.channel_cursors (
    project_id     text NOT NULL,
    channel_id     text NOT NULL,
    last_video_id  text NOT NULL DEFAULT '',
    last_checked   text,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, channel_id)
);

-- ─── Work queue (detect/upload work items) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.work_queue (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  text NOT NULL DEFAULT '',
    work_type   text NOT NULL DEFAULT '',                    -- detect | upload
    status      text NOT NULL DEFAULT 'pending',             -- pending | in_progress | done | failed
    video_id    text NOT NULL DEFAULT '',
    source_url  text NOT NULL DEFAULT '',
    title       text NOT NULL DEFAULT '',
    slot_time   text NOT NULL DEFAULT '',
    error       text NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── Run locks (serializes parallel runs per project) ──────────────────────
CREATE TABLE IF NOT EXISTS public.run_locks (
    project_id   text PRIMARY KEY,
    owner        text NOT NULL DEFAULT '',                   -- "<project_id>:<run_id>"
    acquired_at  timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

-- ─── Run heartbeats (proves a run is alive; used to steal dead-owner locks) ─
CREATE TABLE IF NOT EXISTS public.run_heartbeats (
    project_id  text PRIMARY KEY,
    run_id      text NOT NULL DEFAULT '',                    -- same value as run_locks.owner
    iteration   bigint NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'running',             -- running | done | crashed
    message     text NOT NULL DEFAULT '',
    last_seen   timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── Verify checks (latest result of every bot self-check, per project) ────
CREATE TABLE IF NOT EXISTS public.verify_checks (
    project_id  text NOT NULL,
    check_name  text NOT NULL,
    status      text NOT NULL DEFAULT 'ok',                  -- ok | warn | fail
    message     text NOT NULL DEFAULT '',
    details     jsonb NOT NULL DEFAULT '{}'::jsonb,
    checked_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, check_name)
);

-- ─── Alerts (recurring issues the bot notices, unresolved until fixed) ─────
CREATE TABLE IF NOT EXISTS public.alerts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  text NOT NULL DEFAULT '',
    severity    text NOT NULL DEFAULT 'warn',                -- info | warn | critical
    check_name  text NOT NULL DEFAULT '',
    message     text NOT NULL DEFAULT '',
    details     jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    resolved_by text NOT NULL DEFAULT ''
);

-- ─── Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_upload_logs_project_date
    ON public.upload_logs (project_id, upload_date);
CREATE INDEX IF NOT EXISTS idx_upload_logs_project_source
    ON public.upload_logs (project_id, source_video_id);
CREATE INDEX IF NOT EXISTS idx_work_queue_project_status
    ON public.work_queue (project_id, status);
CREATE INDEX IF NOT EXISTS idx_work_queue_project_created
    ON public.work_queue (project_id, created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_open
    ON public.alerts (project_id, resolved_at);
CREATE INDEX IF NOT EXISTS idx_mirror_state_project
    ON public.mirror_state (project_id, mirrored_video_id);

-- ─── Row Level Security: open access (bot uses service key which bypasses
--     RLS anyway; these policies additionally permit anon/dashboard reads) ─
DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'projects','settings','accounts','channels','channel_cursors',
        'upload_state','upload_logs','mirror_state','mirror_stats',
        'work_queue','run_locks','run_heartbeats','verify_checks','alerts'
    ] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('DROP POLICY IF EXISTS "allow_all_%I" ON public.%I;', t, t);
        EXECUTE format(
            'CREATE POLICY "allow_all_%I" ON public.%I FOR ALL USING (true) WITH CHECK (true);',
            t, t);
    END LOOP;
END $$;

-- ─── Helper view: one row per project with live operational status ────────
CREATE OR REPLACE VIEW public.v_project_status AS
SELECT
    p.id                              AS project_id,
    p.name                            AS project_name,
    p.github_repo                     AS repo,
    p.enabled                         AS enabled,
    p.channels                        AS channels,
    p.uploads_per_day                 AS uploads_per_day,
    p.warmup_days                     AS warmup_days,
    us.total_uploaded                 AS total_uploaded,
    us.last_upload_date               AS last_upload_date,
    CASE WHEN jsonb_typeof(us.processed_hashes) = 'array'
         THEN jsonb_array_length(us.processed_hashes) ELSE 0 END AS processed_count,
    (SELECT count(*)::int FROM public.upload_logs l
      WHERE l.project_id = p.id::text)              AS log_count,
    (SELECT count(*)::int FROM public.upload_logs l
      WHERE l.project_id = p.id::text
        AND l.upload_date = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD'))
                                                     AS today_uploaded,
    (SELECT count(*)::int FROM public.work_queue w
      WHERE w.project_id = p.id::text AND w.status = 'pending')
                                                     AS queued_pending,
    (SELECT count(*)::int FROM public.work_queue w
      WHERE w.project_id = p.id::text AND w.status = 'in_progress')
                                                     AS processing,
    rl.owner                          AS lock_owner,
    rl.expires_at                     AS lock_expires_at,
    hb.run_id                         AS heartbeat_run,
    hb.last_seen                      AS heartbeat_last_seen,
    hb.iteration                      AS heartbeat_iteration,
    p.updated_at                      AS config_updated_at
FROM public.projects p
LEFT JOIN public.upload_state  us ON us.project_id = p.id::text
LEFT JOIN public.run_locks     rl ON rl.project_id = p.id::text
LEFT JOIN public.run_heartbeats hb ON hb.project_id = p.id::text;

-- ─── Helper view: latest verify-check result per project/check ─────────────
CREATE OR REPLACE VIEW public.v_verify_health AS
SELECT
    v.project_id,
    p.name AS project_name,
    count(*) FILTER (WHERE v.status = 'fail')  AS fails,
    count(*) FILTER (WHERE v.status = 'warn')  AS warns,
    count(*) FILTER (WHERE v.status = 'ok')    AS oks,
    max(v.checked_at)                          AS last_checked,
    -- worst status per project ('fail' > 'warn' > 'ok')
    coalesce(
        min(CASE v.status WHEN 'fail' THEN 2 WHEN 'warn' THEN 1 ELSE 0 END),
        0
    )                                          AS worst
FROM public.verify_checks v
LEFT JOIN public.projects p ON p.id::text = v.project_id
GROUP BY v.project_id, p.name;

-- ─── Helper view: unresolved alerts ────────────────────────────────────────
CREATE OR REPLACE VIEW public.v_open_alerts AS
SELECT a.*
FROM public.alerts a
WHERE a.resolved_at IS NULL
ORDER BY a.created_at DESC;
