-- =============================================================================
-- YT VIDEO AUTOMATION — Comprehensive Supabase Schema
-- =============================================================================
-- Single source of truth for the manual upload tool. Every table below is
-- created if it does not already exist; new columns are added when missing;
-- indexes and the helper views are created/replaced idempotently. Safe to run
-- repeatedly.
--
-- RUN: open the Supabase Dashboard SQL Editor for this project and paste the
--      whole file, or run it through the `supabase` CLI / psql. The tool's
--      service key bypasses RLS; the permissive policies below additionally
--      allow the anon role to read state (used by status dashboards).
--
-- 24/7 automation is GONE: the old 24/7 tables (channels, channel_cursors,
-- mirror_state, mirror_stats, work_queue, run_locks, run_heartbeats) and the
-- github/channel/warmup/schedule/proxy project columns are dropped below.
-- =============================================================================

-- ─── Projects (one row per upload project) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.projects (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text NOT NULL,
    yt_client_id        text NOT NULL DEFAULT '',
    yt_client_secret    text NOT NULL DEFAULT '',
    yt_refresh_token    text NOT NULL DEFAULT '',
    account_id          text NOT NULL DEFAULT '',   -- linked accounts.name (upload identity)
    shortlink_provider  text NOT NULL DEFAULT 'vplink',
    shortlink_api_key   text NOT NULL DEFAULT '',
    comment_moderation  text NOT NULL DEFAULT 'heldForReview',
    mirror_title_prefix text NOT NULL DEFAULT '',
    mirror_description_suffix text NOT NULL DEFAULT '',
    custom_title        text NOT NULL DEFAULT '',
    custom_description  text NOT NULL DEFAULT '',
    custom_comment      text NOT NULL DEFAULT '',
    privacy_status      text NOT NULL DEFAULT 'public',
    category_id         text NOT NULL DEFAULT '22',
    enabled             boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Idempotent migrations for columns added after the original deploy
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS account_id text NOT NULL DEFAULT '';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS mirror_description_suffix text NOT NULL DEFAULT '';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS custom_title text NOT NULL DEFAULT '';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS custom_description text NOT NULL DEFAULT '';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS custom_comment text NOT NULL DEFAULT '';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS privacy_status text NOT NULL DEFAULT 'public';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS category_id text NOT NULL DEFAULT '22';

-- Drop the retired 24/7 / GitHub / channel-mirror project columns
ALTER TABLE public.projects DROP COLUMN IF EXISTS github_token;
ALTER TABLE public.projects DROP COLUMN IF EXISTS github_repo;
ALTER TABLE public.projects DROP COLUMN IF EXISTS channels;
ALTER TABLE public.projects DROP COLUMN IF EXISTS warmup_days;
ALTER TABLE public.projects DROP COLUMN IF EXISTS warmup_start;
ALTER TABLE public.projects DROP COLUMN IF EXISTS deployed_at;
ALTER TABLE public.projects DROP COLUMN IF EXISTS uploads_per_day;
ALTER TABLE public.projects DROP COLUMN IF EXISTS initial_backfill;
ALTER TABLE public.projects DROP COLUMN IF EXISTS upload_schedule;
ALTER TABLE public.projects DROP COLUMN IF EXISTS proxy_supabase_url;
ALTER TABLE public.projects DROP COLUMN IF EXISTS proxy_supabase_key;
ALTER TABLE public.projects DROP COLUMN IF EXISTS proxy_enabled;

-- ─── Settings (generic key/value, JSON values) ──────────────────────────────
CREATE TABLE IF NOT EXISTS public.settings (
    key         text PRIMARY KEY,
    value       jsonb NOT NULL DEFAULT 'null'::jsonb,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── Accounts (saved YouTube upload identities — one row per account) ──────
-- Every account the user owns is stored here with its own OAuth credentials,
-- channel identity and health/usage tracking. Projects link to one of these
-- via projects.account_id (the "who uploads" selection system).
CREATE TABLE IF NOT EXISTS public.accounts (
    name             text PRIMARY KEY,                -- user label, e.g. "My Main Channel"
    client_id        text NOT NULL DEFAULT '',
    client_secret    text NOT NULL DEFAULT '',
    refresh_token    text NOT NULL DEFAULT '',
    access_token     text NOT NULL DEFAULT '',        -- transient, optional
    email            text NOT NULL DEFAULT '',        -- Google account email if known
    channel_id       text NOT NULL DEFAULT '',
    channel_name     text NOT NULL DEFAULT '',
    channel_url      text NOT NULL DEFAULT '',
    avatar_url       text NOT NULL DEFAULT '',
    status           text NOT NULL DEFAULT 'active',  -- active | expired | disabled
    last_verified    timestamptz,
    last_error       text NOT NULL DEFAULT '',
    token_expires_at timestamptz,                     -- ~7 days after refresh token issued
    uploads_count    bigint NOT NULL DEFAULT 0,
    notes            text NOT NULL DEFAULT '',
    added_at         text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Idempotent migrations for account columns
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS access_token text NOT NULL DEFAULT '';
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT '';
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS channel_url text NOT NULL DEFAULT '';
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS avatar_url text NOT NULL DEFAULT '';
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS last_verified timestamptz;
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS last_error text NOT NULL DEFAULT '';
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS token_expires_at timestamptz;
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS uploads_count bigint NOT NULL DEFAULT 0;
ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';

-- ─── Per-project upload state ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.upload_state (
    project_id          text PRIMARY KEY,
    account_created     text,
    first_upload_date   text,
    total_uploaded      bigint NOT NULL DEFAULT 0,
    last_upload_date    text,
    last_upload_hour    text,
    processed_hashes    jsonb NOT NULL DEFAULT '[]'::jsonb,  -- source video IDs uploaded
    yt_client_id        text NOT NULL DEFAULT '',
    updated_at          timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.upload_state DROP COLUMN IF EXISTS warmup_start;
ALTER TABLE public.upload_state DROP COLUMN IF EXISTS warmup_complete;
ALTER TABLE public.upload_state DROP COLUMN IF EXISTS filled_slots;
ALTER TABLE public.upload_state DROP COLUMN IF EXISTS filled_slots_date;

-- ─── Upload log (audit trail of every uploaded video) ──────────────────────
CREATE TABLE IF NOT EXISTS public.upload_logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      text NOT NULL DEFAULT '',
    upload_date     text NOT NULL DEFAULT '',                -- YYYY-MM-DD (UTC)
    upload_time     text NOT NULL DEFAULT '',                -- full ISO timestamp
    video_id        text NOT NULL DEFAULT '',                -- the MIRROR video id
    title           text NOT NULL DEFAULT '',
    short_url       text NOT NULL DEFAULT '',
    comment_id      text NOT NULL DEFAULT '',
    source_video_id text NOT NULL DEFAULT '',                -- the SOURCE video id
    source_channel  text NOT NULL DEFAULT '',                -- source channel @handle/id
    account_name    text NOT NULL DEFAULT '',                -- accounts.name that uploaded
    created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.upload_logs ADD COLUMN IF NOT EXISTS source_video_id text NOT NULL DEFAULT '';
ALTER TABLE public.upload_logs ADD COLUMN IF NOT EXISTS source_channel text NOT NULL DEFAULT '';
ALTER TABLE public.upload_logs ADD COLUMN IF NOT EXISTS account_name text NOT NULL DEFAULT '';

-- ─── Verify checks (latest result of every self-check, per project) ────────
CREATE TABLE IF NOT EXISTS public.verify_checks (
    project_id  text NOT NULL,
    check_name  text NOT NULL,
    status      text NOT NULL DEFAULT 'ok',                  -- ok | warn | fail
    message     text NOT NULL DEFAULT '',
    details     jsonb NOT NULL DEFAULT '{}'::jsonb,
    checked_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, check_name)
);

-- ─── Alerts (recurring issues the tool notices, unresolved until fixed) ────
CREATE TABLE IF NOT EXISTS public.alerts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  text NOT NULL DEFAULT '',
    severity    text NOT NULL DEFAULT 'warn',                -- info | warn | critical
    check_name  text NOT NULL DEFAULT '',
    message     text NOT NULL DEFAULT '',
    details     jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    resolved_by text NOT NULL DEFAULT ''
);

-- ─── Retired 24/7 tables ────────────────────────────────────────────────────
DROP TABLE IF EXISTS public.channel_cursors;
DROP TABLE IF EXISTS public.channels;
DROP TABLE IF EXISTS public.mirror_state;
DROP TABLE IF EXISTS public.mirror_stats;
DROP TABLE IF EXISTS public.work_queue;
DROP TABLE IF EXISTS public.run_locks;
DROP TABLE IF EXISTS public.run_heartbeats;

-- ─── Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_upload_logs_project_date
    ON public.upload_logs (project_id, upload_date);
CREATE INDEX IF NOT EXISTS idx_upload_logs_project_source
    ON public.upload_logs (project_id, source_video_id);
CREATE INDEX IF NOT EXISTS idx_alerts_open
    ON public.alerts (project_id, resolved_at);
CREATE INDEX IF NOT EXISTS idx_accounts_status
    ON public.accounts (status);
CREATE INDEX IF NOT EXISTS idx_accounts_channel
    ON public.accounts (channel_id);

-- ─── Row Level Security: open access (tool uses service key which bypasses
--     RLS anyway; these policies additionally permit anon/dashboard reads) ─
DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'projects','settings','accounts',
        'upload_state','upload_logs','verify_checks','alerts'
    ] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('DROP POLICY IF EXISTS "allow_all_%I" ON public.%I;', t, t);
        EXECUTE format(
            'CREATE POLICY "allow_all_%I" ON public.%I FOR ALL USING (true) WITH CHECK (true);',
            t, t);
    END LOOP;
END $$;

-- ─── Helper view: one row per project with current upload status ──────────
CREATE OR REPLACE VIEW public.v_project_status AS
SELECT
    p.id                              AS project_id,
    p.name                            AS project_name,
    p.enabled                         AS enabled,
    p.account_id                      AS upload_account,
    a.channel_name                    AS upload_channel,
    a.status                          AS account_status,
    a.token_expires_at                AS token_expires_at,
    us.total_uploaded                 AS total_uploaded,
    us.last_upload_date               AS last_upload_date,
    -- to_jsonb() handles both jsonb and legacy text[] processed_hashes columns
    CASE WHEN jsonb_typeof(to_jsonb(us.processed_hashes)) = 'array'
         THEN jsonb_array_length(to_jsonb(us.processed_hashes)) ELSE 0 END AS processed_count,
    (SELECT count(*)::int FROM public.upload_logs l
      WHERE l.project_id = p.id::text)              AS log_count,
    (SELECT count(*)::int FROM public.upload_logs l
      WHERE l.project_id = p.id::text
        AND l.upload_date::text = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD'))
                                                     AS today_uploaded,
    p.updated_at                      AS config_updated_at
FROM public.projects p
LEFT JOIN public.accounts    a  ON a.name = p.account_id
LEFT JOIN public.upload_state  us ON us.project_id = p.id::text;

-- ─── Helper view: latest verify-check result per project/check ─────────────
CREATE OR REPLACE VIEW public.v_verify_health AS
SELECT
    v.project_id,
    p.name AS project_name,
    count(*) FILTER (WHERE v.status = 'fail')  AS fails,
    count(*) FILTER (WHERE v.status = 'warn')  AS warns,
    count(*) FILTER (WHERE v.status = 'ok')    AS oks,
    max(v.checked_at)                          AS last_checked,
    -- worst status per project ('fail' > 'warn' > 'ok')
    coalesce(
        min(CASE v.status WHEN 'fail' THEN 2 WHEN 'warn' THEN 1 ELSE 0 END),
        0
    )                                          AS worst
FROM public.verify_checks v
LEFT JOIN public.projects p ON p.id::text = v.project_id
GROUP BY v.project_id, p.name;

-- ─── Helper view: unresolved alerts ────────────────────────────────────────
CREATE OR REPLACE VIEW public.v_open_alerts AS
SELECT a.*
FROM public.alerts a
WHERE a.resolved_at IS NULL
ORDER BY a.created_at DESC;
