import type { PackageDefinition, PackageManagerType } from "../core/types";

export const PACKAGE_REGISTRY: PackageDefinition[] = [
  {
    name: "git",
    displayName: "Git",
    description: "Distributed version control system",
    category: "core",
    required: true,
    detectCommand: "git --version",
    detectVersionFlag: "--version",
    install: {
      apt: "git",
      dnf: "git",
      yum: "git",
      pacman: "git",
      zypper: "git",
      brew: "git",
      winget: "Git.Git",
      pkg: "git",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "curl",
    displayName: "cURL",
    description: "Command line tool for transferring data",
    category: "core",
    required: true,
    detectCommand: "curl --version",
    detectVersionFlag: "--version",
    install: {
      apt: "curl",
      dnf: "curl",
      yum: "curl",
      pacman: "curl",
      zypper: "curl",
      brew: "curl",
      winget: "cURL.cURL",
      pkg: "curl",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "wget",
    displayName: "Wget",
    description: "Network retriever",
    category: "core",
    required: false,
    detectCommand: "wget --version",
    detectVersionFlag: "--version",
    install: {
      apt: "wget",
      dnf: "wget",
      yum: "wget",
      pacman: "wget",
      zypper: "wget",
      brew: "wget",
      winget: "GnuWin32.Wget",
      pkg: "wget",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "unzip",
    displayName: "Unzip",
    description: "Extraction utility for .zip archives",
    category: "core",
    required: false,
    detectCommand: "unzip -v",
    detectVersionFlag: "-v",
    install: {
      apt: "unzip",
      dnf: "unzip",
      yum: "unzip",
      pacman: "unzip",
      zypper: "unzip",
      brew: "unzip",
      winget: "GnuWin32.Unzip",
      pkg: "unzip",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "build-essential",
    displayName: "Build Essential",
    description: "Compilers and build tools (gcc, make, etc.)",
    category: "dev",
    required: false,
    detectCommand: "gcc --version",
    detectVersionFlag: "--version",
    install: {
      apt: "build-essential",
      dnf: "gcc gcc-c++ make",
      yum: "gcc gcc-c++ make",
      pacman: "base-devel",
      zypper: "gcc gcc-c++ make",
      brew: null,
      winget: null,
      pkg: "build-essential",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "nodejs",
    displayName: "Node.js",
    description: "JavaScript runtime",
    category: "languages",
    required: false,
    detectCommand: "node --version",
    detectVersionFlag: "--version",
    install: {
      apt: "nodejs npm",
      dnf: "nodejs npm",
      yum: "nodejs npm",
      pacman: "nodejs npm",
      zypper: "nodejs npm10",
      brew: "node",
      winget: "OpenJS.NodeJS.LTS",
      pkg: "nodejs",
      snap: "node",
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "python3",
    displayName: "Python 3",
    description: "Python programming language",
    category: "languages",
    required: false,
    detectCommand: "python3 --version",
    detectVersionFlag: "--version",
    install: {
      apt: "python3 python3-pip python3-venv",
      dnf: "python3 python3-pip",
      yum: "python3 python3-pip",
      pacman: "python python-pip",
      zypper: "python3 python3-pip",
      brew: "python@3",
      winget: "Python.Python.3.12",
      pkg: "python",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "java",
    displayName: "Java",
    description: "Java Development Kit",
    category: "languages",
    required: false,
    detectCommand: "java -version",
    detectVersionFlag: "-version",
    install: {
      apt: "default-jdk",
      dnf: "java-latest-openjdk-devel",
      yum: "java-11-openjdk-devel",
      pacman: "jdk-openjdk",
      zypper: "java-17-openjdk-devel",
      brew: "openjdk",
      winget: "Microsoft.OpenJDK.21",
      pkg: "openjdk-17",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "docker",
    displayName: "Docker",
    description: "Container runtime",
    category: "containers",
    required: false,
    detectCommand: "docker --version",
    detectVersionFlag: "--version",
    install: {
      apt: "docker.io docker-compose-plugin",
      dnf: "docker docker-compose-plugin",
      yum: "docker docker-compose-plugin",
      pacman: "docker docker-compose",
      zypper: "docker docker-compose",
      brew: "docker docker-compose",
      winget: "Docker.DockerDesktop",
      pkg: null,
      snap: "docker",
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "htop",
    displayName: "htop",
    description: "Interactive process viewer",
    category: "tools",
    required: false,
    detectCommand: "htop --version",
    detectVersionFlag: "--version",
    install: {
      apt: "htop",
      dnf: "htop",
      yum: "htop",
      pacman: "htop",
      zypper: "htop",
      brew: "htop",
      winget: "htop.htop",
      pkg: "htop",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "tmux",
    displayName: "tmux",
    description: "Terminal multiplexer",
    category: "tools",
    required: false,
    detectCommand: "tmux -V",
    detectVersionFlag: "-V",
    install: {
      apt: "tmux",
      dnf: "tmux",
      yum: "tmux",
      pacman: "tmux",
      zypper: "tmux",
      brew: "tmux",
      winget: null,
      pkg: "tmux",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "jq",
    displayName: "jq",
    description: "Command-line JSON processor",
    category: "tools",
    required: false,
    detectCommand: "jq --version",
    detectVersionFlag: "--version",
    install: {
      apt: "jq",
      dnf: "jq",
      yum: "jq",
      pacman: "jq",
      zypper: "jq",
      brew: "jq",
      winget: "jqlang.jq",
      pkg: "jq",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "tree",
    displayName: "Tree",
    description: "Directory tree viewer",
    category: "tools",
    required: false,
    detectCommand: "tree --version",
    detectVersionFlag: "--version",
    install: {
      apt: "tree",
      dnf: "tree",
      yum: "tree",
      pacman: "tree",
      zypper: "tree",
      brew: "tree",
      winget: null,
      pkg: "tree",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "vim",
    displayName: "Vim",
    description: "Text editor",
    category: "editors",
    required: false,
    detectCommand: "vim --version",
    detectVersionFlag: "--version",
    install: {
      apt: "vim",
      dnf: "vim-enhanced",
      yum: "vim-enhanced",
      pacman: "vim",
      zypper: "vim",
      brew: "vim",
      winget: "Vim.Vim",
      pkg: "vim",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "code",
    displayName: "VS Code",
    description: "Visual Studio Code editor",
    category: "editors",
    required: false,
    detectCommand: "code --version",
    detectVersionFlag: "--version",
    install: {
      apt: null,
      dnf: null,
      yum: null,
      pacman: null,
      zypper: null,
      brew: "visual-studio-code",
      winget: "Microsoft.VisualStudioCode",
      pkg: null,
      snap: "code --classic",
      flatpak: "com.visualstudio.code",
      unknown: null,
    },
  },
  {
    name: "rustc",
    displayName: "Rust",
    description: "Rust programming language",
    category: "languages",
    required: false,
    detectCommand: "rustc --version",
    detectVersionFlag: "--version",
    install: {
      apt: null,
      dnf: null,
      yum: null,
      pacman: "rust",
      zypper: null,
      brew: "rust",
      winget: null,
      pkg: null,
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "go",
    displayName: "Go",
    description: "Go programming language",
    category: "languages",
    required: false,
    detectCommand: "go version",
    detectVersionFlag: "version",
    install: {
      apt: "golang",
      dnf: "golang",
      yum: "golang",
      pacman: "go",
      zypper: "go",
      brew: "go",
      winget: "GoLang.Go",
      pkg: "go",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "ruby",
    displayName: "Ruby",
    description: "Ruby programming language",
    category: "languages",
    required: false,
    detectCommand: "ruby --version",
    detectVersionFlag: "--version",
    install: {
      apt: "ruby-full",
      dnf: "ruby",
      yum: "ruby",
      pacman: "ruby",
      zypper: "ruby",
      brew: "ruby",
      winget: "RubyInstallerTeam.Ruby",
      pkg: "ruby",
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "bun",
    displayName: "Bun",
    description: "Fast JavaScript runtime & toolkit",
    category: "languages",
    required: false,
    detectCommand: "bun --version",
    detectVersionFlag: "--version",
    install: {
      apt: null,
      dnf: null,
      yum: null,
      pacman: "bun",
      zypper: null,
      brew: "oven-sh/bun/bun",
      winget: "Oven-sh.Bun",
      pkg: null,
      snap: null,
      flatpak: null,
      unknown: null,
    },
  },
  {
    name: "gh",
    displayName: "GitHub CLI",
    description: "GitHub command-line tool",
    category: "tools",
    required: false,
    detectCommand: "gh --version",
    detectVersionFlag: "--version",
    install: {
      apt: "gh",
      dnf: "gh",
      yum: "gh",
      pacman: "github-cli",
      zypper: "gh",
      brew: "gh",
      winget: "GitHub.cli",
      pkg: "gh",
      snap: "gh",
      flatpak: null,
      unknown: null,
    },
  },
];

export function getPackageByName(name: string): PackageDefinition | undefined {
  return PACKAGE_REGISTRY.find(
    (p) => p.name === name || p.displayName.toLowerCase() === name.toLowerCase()
  );
}

export function getPackagesByCategory(
  category: PackageDefinition["category"]
): PackageDefinition[] {
  return PACKAGE_REGISTRY.filter((p) => p.category === category);
}

export function getRequiredPackages(): PackageDefinition[] {
  return PACKAGE_REGISTRY.filter((p) => p.required);
}

export function searchPackages(query: string): PackageDefinition[] {
  const q = query.toLowerCase();
  return PACKAGE_REGISTRY.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.displayName.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  );
}
